name: Dockerize ML App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerize:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker image
      working-directory: ./webapp
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ml-app:latest .

    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ml-app:latest