name: Dockerize ML App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerize:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker image
      working-directory: ./webapp
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ml-app:latest .

    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ml-app:latest

    - name: Deploy to EC2
      run: |
        # Save the private key to a file
        echo "${{ secrets.EC2_KEY }}" > ec2-key.pem
        chmod 600 ec2-key.pem

        # SSH into EC2 instance
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Stop and remove any running container
          docker stop ml-app || true
          docker rm ml-app || true

          # Pull the latest Docker image
          docker pull ${{ secrets.DOCKER_USERNAME }}/ml-app:latest

          # Run the Docker container
          docker run -d --name ml-app -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/ml-app:latest
        EOF

        # Clean up the private key file
        rm -f ec2-key.pem